version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:management
    hostname: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: "-rabbit disk_free_limit 2147483648"
    env_file:
      - ./.env
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  api:
    build:
      context: .
      args:
        - SERVICE_NAME=api
    restart: always
    ports:
      - ${API_PORT}:${API_PORT}
    depends_on:
      - rabbitmq
    env_file:
      - ./.env

  consumer:
    build:
      context: .
      args:
        - SERVICE_NAME=consumer
    restart: always
    depends_on:
      - rabbitmq
    env_file:
      - ./.env

  websocket:
    build:
      context: .
      args:
        - SERVICE_NAME=ws
    restart: always
    ports:
      - ${WS_PORT}:${WS_PORT}
    env_file:
      - ./.env

volumes:
  rabbitmq_data:
